#!/usr/bin/env bash
# precommit.sh — Pre-commit hook generation (LUMI-inspired prevention)
# Supports two modes:
#   1. .pre-commit-config.yaml generation (pre-commit framework)
#   2. Raw .githooks/pre-commit script (zero-dependency, any git project)

# Detect languages present in the project.
# Sets GK_PC_LANGS as a space-separated list of detected language keys.
_gk_detect_languages() {
  GK_PC_LANGS=""

  # Python
  if [ -f "pyproject.toml" ] || [ -f "requirements.txt" ] || [ -f "setup.py" ] \
      || compgen -G "src/**/*.py" >/dev/null 2>&1 \
      || compgen -G "apps/**/*.py" >/dev/null 2>&1 \
      || find . -maxdepth 3 -name "*.py" -not -path "./.git/*" | grep -q .; then
    GK_PC_LANGS="${GK_PC_LANGS} python"
  fi

  # Rust
  if [ -f "Cargo.toml" ]; then
    GK_PC_LANGS="${GK_PC_LANGS} rust"
  fi

  # Go
  if [ -f "go.mod" ] || [ -f "go.work" ]; then
    GK_PC_LANGS="${GK_PC_LANGS} go"
  fi

  # TypeScript / JavaScript
  if [ -f "package.json" ] || [ -f "tsconfig.json" ]; then
    GK_PC_LANGS="${GK_PC_LANGS} typescript"
  fi

  # Shell
  if find . -maxdepth 3 -name "*.sh" -not -path "./.git/*" | grep -q .; then
    GK_PC_LANGS="${GK_PC_LANGS} shell"
  fi

  # Trim leading whitespace
  GK_PC_LANGS="${GK_PC_LANGS# }"
}

# Emit YAML block for Python hooks.
_gk_pc_block_python() {
  cat <<'YAML'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
YAML
}

# Emit YAML block for Rust hooks.
_gk_pc_block_rust() {
  cat <<'YAML'
  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
YAML
}

# Emit YAML block for TypeScript/JavaScript hooks.
_gk_pc_block_typescript() {
  cat <<'YAML'
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --fix
        language: system
        types_or: [javascript, jsx, ts, tsx]
      - id: tsc
        name: tsc
        entry: npx tsc --noEmit
        language: system
        types_or: [ts, tsx]
        pass_filenames: false
YAML
}

# Emit YAML block for Go hooks.
_gk_pc_block_go() {
  cat <<'YAML'
  - repo: local
    hooks:
      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        types: [go]
        pass_filenames: false
YAML
}

# Emit YAML block for Shell hooks.
_gk_pc_block_shell() {
  cat <<'YAML'
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0
    hooks:
      - id: shellcheck
YAML
}

# Emit the gate-keeper hook block (always appended).
_gk_pc_block_gatekeeper() {
  cat <<'YAML'
  - repo: local
    hooks:
      - id: gate-keeper
        name: gate-keeper layer 1
        entry: gate-keeper run --layer=1 --quiet
        language: system
        pass_filenames: false
        always_run: true
YAML
}

# Main entry point: generate .pre-commit-config.yaml for the current project.
gk_generate_precommit() {
  local output_file=".pre-commit-config.yaml"

  # Guard against overwriting without --force
  if [ -f "$output_file" ] && [ "${GK_FORCE:-false}" != "true" ]; then
    echo "gate-keeper: ${output_file} already exists. Pass GK_FORCE=true to overwrite." >&2
    return 1
  fi

  _gk_detect_languages

  # Build the file header
  {
    cat <<'YAML'
# Generated by gate-keeper init --pre-commit
# See https://pre-commit.com for more information
repos:
YAML

    # Emit language-specific hook blocks in a stable order
    local lang
    for lang in python rust typescript go shell; do
      case " ${GK_PC_LANGS} " in
        *" ${lang} "*)
          case "$lang" in
            python)     _gk_pc_block_python     ;;
            rust)       _gk_pc_block_rust       ;;
            typescript) _gk_pc_block_typescript ;;
            go)         _gk_pc_block_go         ;;
            shell)      _gk_pc_block_shell      ;;
          esac
          ;;
      esac
    done

    # Always append the gate-keeper hook last
    _gk_pc_block_gatekeeper

  } > "$output_file"

  # Build a human-readable list of detected languages for the summary
  local detected_display=""
  for lang in python rust typescript go shell; do
    case " ${GK_PC_LANGS} " in
      *" ${lang} "*)
        local label
        case "$lang" in
          python)     label="Python"     ;;
          rust)       label="Rust"       ;;
          typescript) label="TypeScript" ;;
          go)         label="Go"         ;;
          shell)      label="Shell"      ;;
        esac
        if [ -z "$detected_display" ]; then
          detected_display="$label"
        else
          detected_display="${detected_display}, ${label}"
        fi
        ;;
    esac
  done

  if [ -z "$detected_display" ]; then
    detected_display="(none detected)"
  fi

  echo "Generated ${output_file} with hooks for: ${detected_display}"
  echo "Run 'pre-commit install' to activate hooks"
}

# ═══════════════════════════════════════════════════════════════════════════
# Raw git hook generation — .githooks/pre-commit
# Zero dependency, works with any git project via core.hooksPath
# ═══════════════════════════════════════════════════════════════════════════

# Build the check command block for a language.
# Each block: checks if tool exists, runs the check, captures output to temp file.
_gk_hook_block_python() {
  local ruff_paths="$1"
  local mypy_paths="$2"
  cat <<'HOOK_SH'
  # ── Python ──
  if has_lang "python"; then
    (
      local rc=0
HOOK_SH
  cat <<HOOK_SH
      if command -v ruff >/dev/null 2>&1; then
        ruff check ${ruff_paths} 2>&1 || rc=1
      else
        echo "WARNING: ruff not found, skipping Python lint"
      fi
      if command -v mypy >/dev/null 2>&1; then
        mypy ${mypy_paths} --ignore-missing-imports 2>&1 || rc=1
      else
        echo "WARNING: mypy not found, skipping Python type check"
      fi
HOOK_SH
  cat <<'HOOK_SH'
      exit $rc
    ) > "$TMPDIR/python.log" 2>&1 &
    PIDS+=($!)
    LANGS+=("Python")
  fi
HOOK_SH
}

_gk_hook_block_rust() {
  cat <<'HOOK_SH'
  # ── Rust ──
  if has_lang "rust"; then
    (
      local rc=0
      if command -v cargo >/dev/null 2>&1; then
        cargo clippy --all-targets --all-features -- -D warnings 2>&1 || rc=1
        cargo fmt --all -- --check 2>&1 || rc=1
      else
        echo "WARNING: cargo not found, skipping Rust checks"
      fi
      exit $rc
    ) > "$TMPDIR/rust.log" 2>&1 &
    PIDS+=($!)
    LANGS+=("Rust")
  fi
HOOK_SH
}

_gk_hook_block_typescript() {
  cat <<'HOOK_SH'
  # ── TypeScript / JavaScript ──
  if has_lang "typescript"; then
    (
      local rc=0
      if command -v npx >/dev/null 2>&1; then
        npx eslint . 2>&1 || rc=1
        npx tsc --noEmit 2>&1 || rc=1
      else
        echo "WARNING: npx not found, skipping TypeScript checks"
      fi
      exit $rc
    ) > "$TMPDIR/typescript.log" 2>&1 &
    PIDS+=($!)
    LANGS+=("TypeScript")
  fi
HOOK_SH
}

_gk_hook_block_go() {
  cat <<'HOOK_SH'
  # ── Go ──
  if has_lang "go"; then
    (
      local rc=0
      if command -v go >/dev/null 2>&1; then
        go vet ./... 2>&1 || rc=1
      else
        echo "WARNING: go not found, skipping Go checks"
      fi
      exit $rc
    ) > "$TMPDIR/go.log" 2>&1 &
    PIDS+=($!)
    LANGS+=("Go")
  fi
HOOK_SH
}

_gk_hook_block_shell() {
  cat <<'HOOK_SH'
  # ── Shell ──
  if has_lang "shell"; then
    (
      local rc=0
      if command -v shellcheck >/dev/null 2>&1; then
        local sh_files
        sh_files=$(echo "$STAGED" | grep '\.sh$' || true)
        if [ -n "$sh_files" ]; then
          echo "$sh_files" | xargs shellcheck 2>&1 || rc=1
        fi
      else
        echo "WARNING: shellcheck not found, skipping shell checks"
      fi
      exit $rc
    ) > "$TMPDIR/shell.log" 2>&1 &
    PIDS+=($!)
    LANGS+=("Shell")
  fi
HOOK_SH
}

# Main entry point: generate .githooks/pre-commit raw script.
# Usage: gk_generate_githooks [--setup]
#   --setup: also run git config core.hooksPath .githooks
gk_generate_githooks() {
  local hooks_dir=".githooks"
  local hook_file="${hooks_dir}/pre-commit"
  local do_setup=false

  for arg in "$@"; do
    case "$arg" in
      --setup) do_setup=true ;;
    esac
  done

  # Guard against overwriting without --force
  if [ -f "$hook_file" ] && [ "${GK_FORCE:-false}" != "true" ]; then
    echo "gate-keeper: ${hook_file} already exists. Pass --force to overwrite." >&2
    return 1
  fi

  _gk_detect_languages

  mkdir -p "$hooks_dir"

  # Determine language-specific paths by scanning project structure
  local python_src_dirs=""
  for d in src packages factors apps services; do
    [ -d "$d" ] && python_src_dirs="${python_src_dirs} ${d}"
  done
  python_src_dirs="${python_src_dirs# }"
  [ -z "$python_src_dirs" ] && python_src_dirs="."

  # ── Write the hook script ──
  {
    cat <<'HOOK_HEADER'
#!/usr/bin/env bash
# Generated by gate-keeper init --hooks
# Raw pre-commit hook: staged file detection → language routing → parallel checks
# Bypass: git commit --no-verify
set -euo pipefail

# ── Staged file detection ──
STAGED=$(git diff --cached --name-only --diff-filter=ACM)
[ -z "$STAGED" ] && exit 0

# ── Language routing ──
# Detect which languages are touched by staged files
TOUCHED_LANGS=""
has_lang() { echo "$TOUCHED_LANGS" | grep -qw "$1"; }

echo "$STAGED" | grep -qE '\.py$' && TOUCHED_LANGS="$TOUCHED_LANGS python"
echo "$STAGED" | grep -qE '\.rs$|Cargo\.' && TOUCHED_LANGS="$TOUCHED_LANGS rust"
echo "$STAGED" | grep -qE '\.(ts|tsx|js|jsx)$' && TOUCHED_LANGS="$TOUCHED_LANGS typescript"
echo "$STAGED" | grep -qE '\.go$' && TOUCHED_LANGS="$TOUCHED_LANGS go"
echo "$STAGED" | grep -qE '\.sh$' && TOUCHED_LANGS="$TOUCHED_LANGS shell"

# No recognized language files staged → pass through
[ -z "$TOUCHED_LANGS" ] && exit 0

echo "gate-keeper: pre-commit checks for:${TOUCHED_LANGS}"

# ── Parallel execution with output capture ──
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT
PIDS=()
LANGS=()

HOOK_HEADER

    # Emit language-specific check blocks
    for lang in python rust typescript go shell; do
      case " ${GK_PC_LANGS} " in
        *" ${lang} "*)
          case "$lang" in
            python)     _gk_hook_block_python "$python_src_dirs" "$python_src_dirs" ;;
            rust)       _gk_hook_block_rust       ;;
            typescript) _gk_hook_block_typescript  ;;
            go)         _gk_hook_block_go          ;;
            shell)      _gk_hook_block_shell       ;;
          esac
          ;;
      esac
    done

    # Emit the gate-keeper layer 1 check (always)
    cat <<'HOOK_GK'

  # ── gate-keeper layer 1 ──
  if command -v gate-keeper >/dev/null 2>&1; then
    (
      gate-keeper run --layer=1 --quiet 2>&1 || exit 1
    ) > "$TMPDIR/gate-keeper.log" 2>&1 &
    PIDS+=($!)
    LANGS+=("gate-keeper")
  fi

HOOK_GK

    # Emit the result aggregation block
    cat <<'HOOK_FOOTER'
# ── Wait and aggregate results ──
FINAL_RC=0
for i in "${!PIDS[@]}"; do
  wait "${PIDS[$i]}" || {
    echo ""
    echo "FAIL: ${LANGS[$i]} checks failed:"
    cat "$TMPDIR/$(echo "${LANGS[$i]}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-').log" 2>/dev/null | head -30
    FINAL_RC=1
  }
done

# Print warnings from passing checks (tool-missing notices)
for i in "${!LANGS[@]}"; do
  local logfile="$TMPDIR/$(echo "${LANGS[$i]}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-').log"
  if [ -f "$logfile" ] && grep -q "^WARNING:" "$logfile" 2>/dev/null; then
    grep "^WARNING:" "$logfile"
  fi
done

if [ $FINAL_RC -ne 0 ]; then
  echo ""
  echo "Pre-commit checks failed. Fix the issues above, or bypass with:"
  echo "  git commit --no-verify"
  exit 1
fi

echo "gate-keeper: all checks passed"
HOOK_FOOTER
  } > "$hook_file"

  chmod +x "$hook_file"

  # Build a human-readable list of detected languages
  local detected_display=""
  for lang in python rust typescript go shell; do
    case " ${GK_PC_LANGS} " in
      *" ${lang} "*)
        local label
        case "$lang" in
          python)     label="Python"     ;;
          rust)       label="Rust"       ;;
          typescript) label="TypeScript" ;;
          go)         label="Go"         ;;
          shell)      label="Shell"      ;;
        esac
        if [ -z "$detected_display" ]; then
          detected_display="$label"
        else
          detected_display="${detected_display}, ${label}"
        fi
        ;;
    esac
  done
  [ -z "$detected_display" ] && detected_display="(none detected)"

  echo "Generated ${hook_file} with checks for: ${detected_display}"

  # Optionally set up core.hooksPath
  if [ "$do_setup" = true ]; then
    gk_setup_hooks_path
  else
    echo "Run 'gate-keeper init --setup-hooks' to activate, or manually:"
    echo "  git config core.hooksPath .githooks"
  fi
}

# Configure git to use .githooks/ directory
gk_setup_hooks_path() {
  if ! command -v git >/dev/null 2>&1; then
    echo "git not found" >&2
    return 1
  fi
  if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "Not inside a git repository" >&2
    return 1
  fi
  git config core.hooksPath .githooks
  echo "Git hooks enabled: core.hooksPath → .githooks/"
  echo "All developers run 'git config core.hooksPath .githooks' (or add to Makefile setup target)"
}
